version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: slideconfirm-backend
    ports:
      - "8000:8000"
    volumes:
      - ./data/db:/app/data/db
      - ./data/uploads:/tmp/slideconfirm_uploads
      - ./logs/backend:/app/logs
    environment:
      - DATABASE_URL=sqlite:///./data/db/slideconfirm.db
      - ENVIRONMENT=production
      - LOG_LEVEL=info
      - WORKERS=4
    restart: unless-stopped
    networks:
      - slideconfirm-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: slideconfirm-frontend
    ports:
      - "3000:80"
    volumes:
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - slideconfirm-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  slideconfirm-network:
    driver: bridge

volumes:
  db_data:
    driver: local
  uploads_data:
    driver: local
